In [ ]:
!pip install uv
!uv pip install autogluon

Collecting uv
  Downloading uv-0.12.3-py3-none-win_amd64.whl.metadata (11 kB)
Downloading uv-0.12.3-py3-none-win_amd64.whl (20.2 MB)
   ---------------------------------------- 0.0/20.2 MB ? eta -:--:--
   ----- ---------------------------------- 2.9/20.2 MB 38.6 MB/s eta 0:00:01
   ----------------------- ---------------- 11.8/20.2 MB 40.6 MB/s eta 0:00:01
   ---------------------------------------- 20.2/20.2 MB 39.7 MB/s  0:00:00
Installing collected packages: uv
Successfully installed uv-0.12.3

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
error: No virtual environment found; run `uv venv` to create an environment, or pass `--system` to install into a non-virtual environment

In [2]:
import pandas as pd
train=pd.read_csv('/kaggle/input/competitions/playground-series-s6e5/train.csv')
train.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [ ]:
test=pd.read_csv('/kaggle/input/competitions/playground-series-s6e5/test.csv')
test.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change
0,439140,D119,MEDIUM,British Grand Prix,2023,0,21,1,21.0,4,93.387,0.280,-4.984,0.403846,0.0
1,439141,VER,MEDIUM,Abu Dhabi Grand Prix,2023,0,24,1,24.0,1,90.867,-0.129,-1.990,0.413793,0.0
2,439142,D270,MEDIUM,British Grand Prix,2023,0,24,1,24.0,11,92.871,0.041,-8.842,0.461538,0.0
3,439143,D112,SOFT,São Paulo Grand Prix,2024,0,6,2,4.0,15,94.967,-19.741,8.250,0.077922,1.0
4,439144,AND,HARD,United States Grand Prix,2024,0,52,2,29.0,12,99.112,0.930,-20.848,0.722222,7.0

In [ ]:
org=pd.read_csv('/kaggle/input/datasets/aadigupta1601/f1-strategy-dataset-pit-stop-prediction/f1_strategy_dataset_v4.csv')
org.head()

,Driver,LapNumber,Compound,Stint,TyreLife,Position,LapTime (s),Race,Year,LapTime_Delta,Cumulative_Degradation,PitStop,PitNextLap,RaceProgress,Normalized_TyreLife,Position_Change
0,ALB,1,MEDIUM,1,2.0,17,100.625,Abu Dhabi Grand Prix,2023,0.000,0.000,0,0,0.017241,0.117647,0.0
1,ALB,2,MEDIUM,1,3.0,18,93.560,Abu Dhabi Grand Prix,2023,-7.065,-7.065,0,0,0.034483,0.176471,-1.0
2,ALB,3,MEDIUM,1,4.0,18,91.768,Abu Dhabi Grand Prix,2023,-1.792,-8.857,0,0,0.051724,0.235294,0.0
3,ALB,4,MEDIUM,1,5.0,18,91.591,Abu Dhabi Grand Prix,2023,-0.177,-9.034,0,0,0.068966,0.294118,0.0
4,ALB,5,MEDIUM,1,6.0,18,91.422,Abu Dhabi Grand Prix,2023,-0.169,-9.203,0,0,0.086207,0.352941,0.0

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439140 entries, 0 to 439139
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      439140 non-null  int64
 1   Driver                  439140 non-null  object
 2   Compound                439140 non-null  object
 3   Race                    439140 non-null  object
 4   Year                    439140 non-null  int64
 5   PitStop                 439140 non-null  int64
 6   LapNumber               439140 non-null  int64
 7   Stint                   439140 non-null  int64
 8   TyreLife                439140 non-null  float64
 9   Position                439140 non-null  int64
 10  LapTime (s)             439140 non-null  float64
 11  LapTime_Delta           439140 non-null  float64
 12  Cumulative_Degradation  439140 non-null  float64
 13  RaceProgress            439140 non-null  float64
 14  Position_Change         439140 non-null  float64
 15  PitNextLap              439140 non-null  float64
dtypes: float64(7), int64(6), object(3)
memory usage: 53.6+ MB

In [ ]:
train.nunique()

id                        439140
Driver                       887
Compound                       5
Race                          26
Year                           4
PitStop                        2
LapNumber                     78
Stint                          8
TyreLife                      78
Position                      20
LapTime (s)                37719
LapTime_Delta              57532
Cumulative_Degradation    142701
RaceProgress                1898
Position_Change               37
PitNextLap                     2
dtype: int64

In [ ]:
train=train.drop(['id'],axis=1)
train.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [ ]:
test=test.drop(['id'],axis=1)
test.head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change
0,D119,MEDIUM,British Grand Prix,2023,0,21,1,21.0,4,93.387,0.280,-4.984,0.403846,0.0
1,VER,MEDIUM,Abu Dhabi Grand Prix,2023,0,24,1,24.0,1,90.867,-0.129,-1.990,0.413793,0.0
2,D270,MEDIUM,British Grand Prix,2023,0,24,1,24.0,11,92.871,0.041,-8.842,0.461538,0.0
3,D112,SOFT,São Paulo Grand Prix,2024,0,6,2,4.0,15,94.967,-19.741,8.250,0.077922,1.0
4,AND,HARD,United States Grand Prix,2024,0,52,2,29.0,12,99.112,0.930,-20.848,0.722222,7.0

In [9]:
org=org.drop(['Normalized_TyreLife'],axis=1)
org.head()

,Driver,LapNumber,Compound,Stint,TyreLife,Position,LapTime (s),Race,Year,LapTime_Delta,Cumulative_Degradation,PitStop,PitNextLap,RaceProgress,Position_Change
0,ALB,1,MEDIUM,1,2.0,17,100.625,Abu Dhabi Grand Prix,2023,0.000,0.000,0,0,0.017241,0.0
1,ALB,2,MEDIUM,1,3.0,18,93.560,Abu Dhabi Grand Prix,2023,-7.065,-7.065,0,0,0.034483,-1.0
2,ALB,3,MEDIUM,1,4.0,18,91.768,Abu Dhabi Grand Prix,2023,-1.792,-8.857,0,0,0.051724,0.0
3,ALB,4,MEDIUM,1,5.0,18,91.591,Abu Dhabi Grand Prix,2023,-0.177,-9.034,0,0,0.068966,0.0
4,ALB,5,MEDIUM,1,6.0,18,91.422,Abu Dhabi Grand Prix,2023,-0.169,-9.203,0,0,0.086207,0.0

In [10]:
train=pd.concat([train, org], axis=0)
train=train.sample(frac=1)
train.reset_index(drop=True,inplace=True)
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540511 entries, 0 to 540510
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Driver                  540511 non-null  object
 1   Compound                540445 non-null  object
 2   Race                    540511 non-null  object
 3   Year                    540511 non-null  int64
 4   PitStop                 540511 non-null  int64
 5   LapNumber               540511 non-null  int64
 6   Stint                   540511 non-null  int64
 7   TyreLife                540511 non-null  float64
 8   Position                540511 non-null  int64
 9   LapTime (s)             540511 non-null  float64
 10  LapTime_Delta           540511 non-null  float64
 11  Cumulative_Degradation  540511 non-null  float64
 12  RaceProgress            540511 non-null  float64
 13  Position_Change         540511 non-null  float64
 14  PitNextLap              540511 non-null  float64
dtypes: float64(7), int64(5), object(3)
memory usage: 61.9+ MB

In [11]:
train.describe()

,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
count,540511.000000,540511.000000,540511.000000,540511.000000,540511.000000,540511.000000,540511.000000,540511.000000,540511.000000,540511.000000,540511.000000,540511.000000
mean,2023.535948,0.157773,24.482301,1.837365,14.231582,9.654494,91.256021,-3.101221,-26.439742,0.355470,0.081628,0.209450
std,1.039448,0.364528,17.424550,0.955225,9.900556,5.303185,22.916342,44.233406,58.002225,0.256883,3.989509,0.406916
min,2022.000000,0.000000,1.000000,1.000000,1.000000,1.000000,67.012000,-2403.895000,-274.564000,0.012821,-18.000000,0.000000
25%,2023.000000,0.000000,10.000000,1.000000,6.000000,5.000000,82.430000,-8.717000,-47.611500,0.141026,-1.000000,0.000000
50%,2024.000000,0.000000,21.000000,2.000000,12.000000,10.000000,90.648000,-0.226000,-21.068000,0.294872,0.000000,0.000000
75%,2024.000000,0.000000,38.000000,2.000000,20.000000,14.000000,98.632000,0.338000,-5.918000,0.541667,2.000000,0.000000
max,2025.000000,1.000000,78.000000,8.000000,78.000000,20.000000,2526.253000,2433.472000,2412.431000,1.000000,18.000000,1.000000

In [12]:
train.isnull().sum()

Driver                     0
Compound                  66
Race                       0
Year                       0
PitStop                    0
LapNumber                  0
Stint                      0
TyreLife                   0
Position                   0
LapTime (s)                0
LapTime_Delta              0
Cumulative_Degradation     0
RaceProgress               0
Position_Change            0
PitNextLap                 0
dtype: int64

In [13]:
round(train.isnull().sum()*100/len(train),2)

Driver                    0.00
Compound                  0.01
Race                      0.00
Year                      0.00
PitStop                   0.00
LapNumber                 0.00
Stint                     0.00
TyreLife                  0.00
Position                  0.00
LapTime (s)               0.00
LapTime_Delta             0.00
Cumulative_Degradation    0.00
RaceProgress              0.00
Position_Change           0.00
PitNextLap                0.00
dtype: float64

In [14]:
train[train.isna().any(axis=1)].head()

,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
884,RUS,NaN,Austrian Grand Prix,2022,0,59,3,22.0,5,77.703,0.821,-106.457,0.819444,-1.0,1.0
5595,STR,NaN,Monaco Grand Prix,2022,0,46,5,23.0,14,79.604,0.074,-24.229,0.638889,0.0,0.0
9759,RUS,NaN,Austrian Grand Prix,2022,0,48,3,11.0,7,70.454,-6.602,-95.633,0.666667,-3.0,1.0
55336,RUS,NaN,Austrian Grand Prix,2022,1,45,3,8.0,7,70.296,-37.442,-95.791,0.625000,-4.0,1.0
55964,RUS,NaN,Austrian Grand Prix,2022,0,54,3,17.0,6,70.004,-69.903,-114.156,0.750000,-2.0,1.0

In [15]:
counter=0
for i in test.select_dtypes(include=['object']).columns.tolist():
    if (len(list(set(train[i].unique().tolist())^set(test[i].unique().tolist())))!=0):
        print(i ,'need to be worked on')
        counter+=1
    else:
        continue
if(counter==0):
    print('No work needed')

Driver need to be worked on
Compound need to be worked on
Race need to be worked on

In [16]:
Driver=train['Driver'].value_counts().to_frame()
Driver.reset_index()

    Driver  count
0      NOR   6999
1      VER   6845
2      RUS   6738
3      HAM   6593
4      LEC   6587
..     ...    ...
882   D684      1
883   D749      1
884   D705      1
885   D713      1
886   D742      1

[887 rows x 2 columns]

In [17]:
list(set(train['Driver'].unique().tolist())^set(test['Driver'].unique().tolist()))[:5]

['D636', 'D723', 'D610', 'D667', 'D729']

In [18]:
train['Driver'].unique().tolist()[:5]

['WAR', 'D208', 'BUE', 'D030', 'FUJ']

In [19]:
train=train.drop(['Driver'],axis=1)
train.head()

,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,MEDIUM,Miami Grand Prix,2022,0,10,1,10.0,8,95.567,-0.050,-46.848,0.138889,1.0,0.0
1,HARD,Qatar Grand Prix,2025,0,44,3,12.0,7,84.068,3.937,-50.939,0.578947,9.0,0.0
2,HARD,Miami Grand Prix,2025,1,46,2,23.0,15,91.967,-2.606,-201.184,0.638889,-1.0,1.0
3,MEDIUM,Las Vegas Grand Prix,2023,0,7,1,7.0,7,103.531,0.000,-6.904,0.140000,0.0,0.0
4,HARD,Mexico City Grand Prix,2022,1,35,2,10.0,10,83.966,-60.601,-35.079,0.486111,-4.0,0.0

In [20]:
test=test.drop(['Driver'],axis=1)
test.head()

,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change
0,MEDIUM,British Grand Prix,2023,0,21,1,21.0,4,93.387,0.280,-4.984,0.403846,0.0
1,MEDIUM,Abu Dhabi Grand Prix,2023,0,24,1,24.0,1,90.867,-0.129,-1.990,0.413793,0.0
2,MEDIUM,British Grand Prix,2023,0,24,1,24.0,11,92.871,0.041,-8.842,0.461538,0.0
3,SOFT,São Paulo Grand Prix,2024,0,6,2,4.0,15,94.967,-19.741,8.250,0.077922,1.0
4,HARD,United States Grand Prix,2024,0,52,2,29.0,12,99.112,0.930,-20.848,0.722222,7.0

In [21]:
Compound=train['Compound'].value_counts().to_frame()
Compound.reset_index()

       Compound   count
0        MEDIUM  248780
1          HARD  215485
2          SOFT   51488
3  INTERMEDIATE   22938
4           WET    1754

In [22]:
Race=train['Race'].value_counts().to_frame()
Race.reset_index()

                         Race  count
0            Dutch Grand Prix  29948
1      Mexico City Grand Prix  28777
2        Hungarian Grand Prix  27838
3           Monaco Grand Prix  26703
4         Canadian Grand Prix  26570
5         Austrian Grand Prix  26069
6          Pre-Season Testing  25863
7          Spanish Grand Prix  25537
8          Bahrain Grand Prix  23950
9          Italian Grand Prix  23752
10       Singapore Grand Prix  23264
11           Miami Grand Prix  22682
12      Australian Grand Prix  22181
13   United States Grand Prix  22074
14   Saudi Arabian Grand Prix  21541
15       Abu Dhabi Grand Prix  19773
16  Emilia Romagna Grand Prix  19051
17         British Grand Prix  18816
18           Qatar Grand Prix  16804
19        Japanese Grand Prix  16077
20      Azerbaijan Grand Prix  15790
21       Las Vegas Grand Prix  15162
22       São Paulo Grand Prix  14932
23         Belgian Grand Prix  12153
24         Chinese Grand Prix   9383
25          French Grand Prix   4130
26            Pre-Season Test    918
27   Pre-Season Track Session    773

In [23]:
train.duplicated().value_counts()

False    540494
True         17
Name: count, dtype: int64

In [24]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [25]:
label = 'PitNextLap'
train[label].value_counts()

PitNextLap
0.0    427301
1.0    113210
Name: count, dtype: int64

In [26]:
predictor = TabularPredictor(label=label,eval_metric='roc_auc').fit(
    train_data=train,
    ag_args_fit={"num_gpus": 2},
    time_limit=3600*9,
    presets='best_quality',
    verbosity=3,
    num_stack_levels=0
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260508_171648"
Verbosity: 3 (Detailed Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          4
Pytorch Version:    2.9.1+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.56/14.56 GB | GPU 1: 14.56/14.56 GB
Total GPU Memory:   Free: 29.13 GB, Allocated: 0.00 GB, Total: 29.13 GB
GPU Count:          2
Memory Avail:       29.49 GB / 31.35 GB (94.1%)
Disk Space Avail:   19.50 GB / 19.52 GB (99.9%)
===================================================
Presets specified: ['best_quality']
============ fit kwarg info ============
User Specified kwargs:
{'ag_args_fit': {'num_gpus': 2},
 'auto_stack': True,
 'num_stack_levels': 0,
 'verbosity': 3}
Full kwargs:
{'_experimental_dynamic_hyperparameters': False,
 '_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': {'num_gpus': 2},
 'auto_stack': True,
 'calibrate': 'auto',
 'delay_bag_sets': False,
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'enable_callbacks': True,
             'enable_ray_logging': True,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': 'auto',
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': None,
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': None,
 'included_model_types': None,
 'keep_only_best': False,
 'learning_curves': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': 0,
 'pseudo_data': None,
 'raise_on_model_failure': False,
 'raise_on_no_models_fitted': True,
 'refit_full': False,
 'save_bag_folds': None,
 'save_space': False,
 'set_best_to_refit_full': False,
 'test_data': None,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'verbosity': 3}
========================================
Using hyperparameters preset: hyperparameters='zeroshot'
Stack configuration (auto_stack=True): num_stack_levels=0, num_bag_folds=8, num_bag_sets=1
Saving /kaggle/working/AutogluonModels/ag-20260508_171648/learner.pkl
Saving /kaggle/working/AutogluonModels/ag-20260508_171648/predictor.pkl
Beginning AutoGluon training ... Time limit = 32400s
AutoGluon will save models to "/kaggle/working/AutogluonModels/ag-20260508_171648"
Train Data Rows:    540511
Train Data Columns: 13
Label Column:       PitNextLap
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [np.float64(0.0), np.float64(1.0)]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    30198.76 MB
	Train Data (Original)  Memory Usage: 109.08 MB (0.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
			Original Features (exact raw dtype, raw dtype):
				('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', 'object') : 2 | ['Compound', 'Race']
			Types of features in original data (raw dtype, special dtypes):
				('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			0.2s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
				('object', [])    : 2 | ['Compound', 'Race']
			0.2s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			11 features in original data used to generate 11 features in processed data.
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
				Types of features in original data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				Types of features in processed data (raw dtype, special dtypes):
					('category', []) : 2 | ['Compound', 'Race']
				0.1s = Fit runtime
				2 features in original data used to generate 2 features in processed data.
			Types of features in original data (raw dtype, special dtypes):
				('object', []) : 2 | ['Compound', 'Race']
			Types of features in processed data (raw dtype, special dtypes):
				('category', []) : 2 | ['Compound', 'Race']
			0.3s = Fit runtime
			2 features in original data used to generate 2 features in processed data.
		Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
		Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
		Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
		Skipping IdentityFeatureGenerator: No input feature with required dtypes.
		Skipping IsNanFeatureGenerator: No input feature with required dtypes.
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.2s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
			Types of features in original data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			Types of features in processed data (raw dtype, special dtypes):
				('category', [])  : 2 | ['Compound', 'Race']
				('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
				('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
				('int', ['bool']) : 1 | ['PitStop']
			0.1s = Fit runtime
			13 features in original data used to generate 13 features in processed data.
	Types of features in original data (exact raw dtype, raw dtype):
		('float64', 'float') : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')     : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', 'object') : 2 | ['Compound', 'Race']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])    : 5 | ['Year', 'PitStop', 'LapNumber', 'Stint', 'Position']
		('object', []) : 2 | ['Compound', 'Race']
	Types of features in processed data (exact raw dtype, raw dtype):
		('category', 'category') : 2 | ['Compound', 'Race']
		('float64', 'float')     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int64', 'int')         : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int8', 'int')          : 1 | ['PitStop']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 2 | ['Compound', 'Race']
		('float', [])     : 6 | ['TyreLife', 'LapTime (s)', 'LapTime_Delta', 'Cumulative_Degradation', 'RaceProgress', ...]
		('int', [])       : 4 | ['Year', 'LapNumber', 'Stint', 'Position']
		('int', ['bool']) : 1 | ['PitStop']
	1.6s = Fit runtime
	13 features in original data used to generate 13 features in processed data.
	Train Data (Processed) Memory Usage: 42.79 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 1.79s ...
AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'
	This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
	To change this, specify the eval_metric parameter of Predictor()
Saving /kaggle/working/AutogluonModels/ag-20260508_171648/learner.pkl
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}, {'activation': 'elu', 'dropout_prob': 0.24622382571353768, 'hidden_size': 159, 'learning_rate': 0.008507536855608535, 'num_layers': 5, 'use_batchnorm': True, 'weight_decay': 1.8201539594953562e-06, 'ag_args': {'name_suffix': '_r30', 'priority': -17}}, {'activation': 'relu', 'dropout_prob': 0.09976801642258049, 'hidden_size': 135, 'learning_rate': 0.001631450730978947, 'num_layers': 5, 'use_batchnorm': False, 'weight_decay': 3.867683394425807e-05, 'ag_args': {'name_suffix': '_r86', 'priority': -19}}, {'activation': 'relu', 'dropout_prob': 0.3905837860053583, 'hidden_size': 106, 'learning_rate': 0.0018297905295930797, 'num_layers': 1, 'use_batchnorm': True, 'weight_decay': 9.178069874232892e-08, 'ag_args': {'name_suffix': '_r14', 'priority': -26}}, {'activation': 'relu', 'dropout_prob': 0.05488816803887784, 'hidden_size': 32, 'learning_rate': 0.0075612897834015985, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.652353009917866e-08, 'ag_args': {'name_suffix': '_r41', 'priority': -35}}, {'activation': 'elu', 'dropout_prob': 0.01030258381183309, 'hidden_size': 111, 'learning_rate': 0.01845979186513771, 'num_layers': 5, 'use_batchnorm': True, 'weight_decay': 0.00020238017476912164, 'ag_args': {'name_suffix': '_r158', 'priority': -38}}, {'activation': 'elu', 'dropout_prob': 0.18109219857068798, 'hidden_size': 250, 'learning_rate': 0.00634181748507711, 'num_layers': 1, 'use_batchnorm': False, 'weight_decay': 5.3861175580695396e-08, 'ag_args': {'name_suffix': '_r197', 'priority': -41}}, {'activation': 'elu', 'dropout_prob': 0.1703783780377607, 'hidden_size': 212, 'learning_rate': 0.0004107199833213839, 'num_layers': 5, 'use_batchnorm': True, 'weight_decay': 1.105439140660822e-07, 'ag_args': {'name_suffix': '_r143', 'priority': -49}}, {'activation': 'elu', 'dropout_prob': 0.013288954106470907, 'hidden_size': 81, 'learning_rate': 0.005340914647396154, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 8.762168370775353e-05, 'ag_args': {'name_suffix': '_r31', 'priority': -52}}, {'activation': 'relu', 'dropout_prob': 0.36669080773207274, 'hidden_size': 95, 'learning_rate': 0.015280159186761077, 'num_layers': 3, 'use_batchnorm': True, 'weight_decay': 1.3082489374636015e-08, 'ag_args': {'name_suffix': '_r87', 'priority': -59}}, {'activation': 'relu', 'dropout_prob': 0.3027114570947557, 'hidden_size': 196, 'learning_rate': 0.006482759295309238, 'num_layers': 1, 'use_batchnorm': False, 'weight_decay': 1.2806509958776e-12, 'ag_args': {'name_suffix': '_r71', 'priority': -60}}, {'activation': 'relu', 'dropout_prob': 0.12166942295569863, 'hidden_size': 151, 'learning_rate': 0.0018866871631794007, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 9.190843763153802e-05, 'ag_args': {'name_suffix': '_r185', 'priority': -65}}, {'activation': 'relu', 'dropout_prob': 0.006531401073483156, 'hidden_size': 192, 'learning_rate': 0.012418052210914356, 'num_layers': 1, 'use_batchnorm': True, 'weight_decay': 3.0406866089493607e-05, 'ag_args': {'name_suffix': '_r76', 'priority': -77}}, {'activation': 'relu', 'dropout_prob': 0.33926015213879396, 'hidden_size': 247, 'learning_rate': 0.0029983839090226075, 'num_layers': 5, 'use_batchnorm': False, 'weight_decay': 0.00038926240517691234, 'ag_args': {'name_suffix': '_r121', 'priority': -79}}, {'activation': 'elu', 'dropout_prob': 0.06134755114373829, 'hidden_size': 144, 'learning_rate': 0.005834535148903801, 'num_layers': 5, 'use_batchnorm': True, 'weight_decay': 2.0826540090463355e-09, 'ag_args': {'name_suffix': '_r135', 'priority': -84}}, {'activation': 'elu', 'dropout_prob': 0.3457125770744979, 'hidden_size': 37, 'learning_rate': 0.006435774191713849, 'num_layers': 3, 'use_batchnorm': True, 'weight_decay': 2.4012185204155345e-08, 'ag_args': {'name_suffix': '_r36', 'priority': -87}}, {'activation': 'relu', 'dropout_prob': 0.2211285919550286, 'hidden_size': 196, 'learning_rate': 0.011307978270179143, 'num_layers': 1, 'use_batchnorm': True, 'weight_decay': 1.8441764217351068e-06, 'ag_args': {'name_suffix': '_r19', 'priority': -92}}, {'activation': 'relu', 'dropout_prob': 0.23713784729000734, 'hidden_size': 200, 'learning_rate': 0.00311256170909018, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 4.573016756474468e-08, 'ag_args': {'name_suffix': '_r1', 'priority': -96}}, {'activation': 'relu', 'dropout_prob': 0.33567564890346097, 'hidden_size': 245, 'learning_rate': 0.006746560197328548, 'num_layers': 3, 'use_batchnorm': True, 'weight_decay': 1.6470047305392933e-10, 'ag_args': {'name_suffix': '_r89', 'priority': -97}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}, {'extra_trees': False, 'feature_fraction': 0.7023601671276614, 'learning_rate': 0.012144796373999013, 'min_data_in_leaf': 14, 'num_leaves': 53, 'ag_args': {'name_suffix': '_r131', 'priority': -3}}, {'extra_trees': True, 'feature_fraction': 0.5636931414546802, 'learning_rate': 0.01518660230385841, 'min_data_in_leaf': 48, 'num_leaves': 16, 'ag_args': {'name_suffix': '_r96', 'priority': -6}}, {'extra_trees': True, 'feature_fraction': 0.8282601210460099, 'learning_rate': 0.033929021353492905, 'min_data_in_leaf': 6, 'num_leaves': 127, 'ag_args': {'name_suffix': '_r188', 'priority': -14}}, {'extra_trees': False, 'feature_fraction': 0.6245777099925497, 'learning_rate': 0.04711573688184715, 'min_data_in_leaf': 56, 'num_leaves': 89, 'ag_args': {'name_suffix': '_r130', 'priority': -18}}, {'extra_trees': False, 'feature_fraction': 0.5898927512279213, 'learning_rate': 0.010464516487486093, 'min_data_in_leaf': 11, 'num_leaves': 252, 'ag_args': {'name_suffix': '_r161', 'priority': -27}}, {'extra_trees': True, 'feature_fraction': 0.5143401489640409, 'learning_rate': 0.00529479887023554, 'min_data_in_leaf': 6, 'num_leaves': 133, 'ag_args': {'name_suffix': '_r196', 'priority': -31}}, {'extra_trees': False, 'feature_fraction': 0.7421180622507277, 'learning_rate': 0.018603888565740096, 'min_data_in_leaf': 6, 'num_leaves': 22, 'ag_args': {'name_suffix': '_r15', 'priority': -37}}, {'extra_trees': False, 'feature_fraction': 0.9408897917880529, 'learning_rate': 0.01343464462043561, 'min_data_in_leaf': 21, 'num_leaves': 178, 'ag_args': {'name_suffix': '_r143', 'priority': -44}}, {'extra_trees': True, 'feature_fraction': 0.4341088458599442, 'learning_rate': 0.04034449862560467, 'min_data_in_leaf': 33, 'num_leaves': 16, 'ag_args': {'name_suffix': '_r94', 'priority': -48}}, {'extra_trees': True, 'feature_fraction': 0.9773131270704629, 'learning_rate': 0.010534290864227067, 'min_data_in_leaf': 21, 'num_leaves': 111, 'ag_args': {'name_suffix': '_r30', 'priority': -56}}, {'extra_trees': False, 'feature_fraction': 0.8254432681390782, 'learning_rate': 0.031251656439648626, 'min_data_in_leaf': 50, 'num_leaves': 210, 'ag_args': {'name_suffix': '_r135', 'priority': -69}}, {'extra_trees': False, 'feature_fraction': 0.5730390983988963, 'learning_rate': 0.010305352949119608, 'min_data_in_leaf': 10, 'num_leaves': 215, 'ag_args': {'name_suffix': '_r121', 'priority': -74}}, {'extra_trees': True, 'feature_fraction': 0.4601361323873807, 'learning_rate': 0.07856777698860955, 'min_data_in_leaf': 12, 'num_leaves': 198, 'ag_args': {'name_suffix': '_r42', 'priority': -95}}],

In [27]:
predictor.leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,0.959526,roc_auc,1130.212468,25951.266641,0.117288,42.174004,2,True,15
1,LightGBMLarge_BAG_L1,0.957849,roc_auc,235.167225,1820.700437,235.167225,1820.700437,1,True,11
2,LightGBM_BAG_L1,0.957187,roc_auc,294.966462,2246.945969,294.966462,2246.945969,1,True,2
3,XGBoost_BAG_L1,0.956181,roc_auc,1.448842,153.781862,1.448842,153.781862,1,True,9
4,LightGBMXT_BAG_L1,0.955574,roc_auc,574.071145,3024.799127,574.071145,3024.799127,1,True,1
5,NeuralNetTorch_BAG_L1,0.953780,roc_auc,2.237780,18478.818344,2.237780,18478.818344,1,True,10
6,RandomForestEntr_BAG_L1,0.953409,roc_auc,22.203726,184.046897,22.203726,184.046897,1,True,4
7,RandomForestGini_BAG_L1,0.951480,roc_auc,19.398668,146.512406,19.398668,146.512406,1,True,3
8,CatBoost_BAG_L1,0.950769,roc_auc,1.937761,740.843478,1.937761,740.843478,1,True,5
9,NeuralNetTorch_r79_BAG_L1,0.949325,roc_auc,2.463107,2193.111301,2.463107,2193.111301,1,True,13
10,LightGBM_r131_BAG_L1,0.948419,roc_auc,91.522191,557.122025,91.522191,557.122025,1,True,14
11,NeuralNetFastAI_BAG_L1,0.947651,roc_auc,4.196470,2344.744061,4.196470,2344.744061,1,True,8
12,ExtraTreesEntr_BAG_L1,0.941309,roc_auc,19.628207,57.113208,19.628207,57.113208,1,True,7
13,CatBoost_r177_BAG_L1,0.939805,roc_auc,0.470685,128.792324,0.470685,128.792324,1,True,12
14,ExtraTreesGini_BAG_L1,0.938942,roc_auc,18.238818,51.178350,18.238818,51.178350,1,True,6

In [28]:
df=predictor.predict_proba(test)
df.head()

Loading: /kaggle/working/AutogluonModels/ag-20260508_171648/models/LightGBMLarge_BAG_L1/model.pkl
Loading: /kaggle/working/AutogluonModels/ag-20260508_171648/models/LightGBMXT_BAG_L1/model.pkl
Loading: /kaggle/working/AutogluonModels/ag-20260508_171648/models/LightGBM_BAG_L1/model.pkl
Loading: /kaggle/working/AutogluonModels/ag-20260508_171648/models/NeuralNetTorch_BAG_L1/model.pkl
Loading: /kaggle/working/AutogluonModels/ag-20260508_171648/models/RandomForestEntr_BAG_L1/model.pkl
Loading: /kaggle/working/AutogluonModels/ag-20260508_171648/models/XGBoost_BAG_L1/model.pkl
Loading: /kaggle/working/AutogluonModels/ag-20260508_171648/models/WeightedEnsemble_L2/model.pkl

          0         1
0  0.996667  0.003333
1  0.995125  0.004875
2  0.997395  0.002605
3  0.767716  0.232284
4  0.084054  0.915946

In [29]:
sol=pd.read_csv('/kaggle/input/competitions/playground-series-s6e5/sample_submission.csv')
sol.head()

       id  PitNextLap
0  439140           0
1  439141           0
2  439142           0
3  439143           0
4  439144           0

In [30]:
sol['PitNextLap']=df[1]
sol.head()

       id  PitNextLap
0  439140    0.003333
1  439141    0.004875
2  439142    0.002605
3  439143    0.232284
4  439144    0.915946

In [31]:
sol.to_csv("best_quality.csv", index=False)